# 监控配置
monitoring:
  check_interval: 5  # 检查间隔(秒)
  max_samples: 1000  # 最大样本数

# 流地址配置
streams:
  - id: "video1"
    url: "https://bt-01-pull.g33-video.com/nw35/8-351.flv"


# 报警配置
webhook:
  enabled: true
  url: "http://localhost:8080/alerts"
