# 监控配置
monitoring:
  check_interval: 10  # 检查间隔(秒)
  max_samples: 1000  # 最大样本数

# 流地址配置
streams:
  - id: "videoId1"
    name: "demo1"
    url: "https://demo1.com/nw27/8-271.flv"
  - id: "videoId2"
    name: "demo2"
    url: "https://demo2.com/nw27/8-271.flv"


# 报警配置
webhook:
  enabled: false
  url: "http://127.0.0.1:8080/alert"
